First job/scheduler creation model
beoboo/job-scheduler-library pull request #1
Opened 2021-11-30 16:59 UTC by beoboo

2021-11-30 18:18 UTC, zmb3 requested changes
Left a few comments. The race detector also picked up at least one data race, so I would recommend fixing that too.

2021-12-01 23:52 UTC, timothyb89 approved these changes
Looks much better, thanks!

2021-12-02 16:05 UTC, zmb3 approved these changes

2021-12-02 17:45 UTC, smallinsky approved these changes

2021-12-02 17:48 UTC, merged